[tool.poetry]
name = "dinrplan"
version = "0.1.0"
description = ""
authors = ["Filip Lange <filip.lange@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.9"
django-heroku = "^0.3.1"
psycopg2-binary = "2.9.1"
python-dotenv = "^0.19.2"
gunicorn = "^20.1.0"
pre-commit = "^2.15.0"
coverage = "^6.1.2"
playwright = "^1.17.0"
pytest = "^6.2.5"
pytest-django = "^4.4.0"
pytest-playwright = "^0.2.2"

[tool.poetry.dev-dependencies]
black = {extras = ["d"], version = "^21.10b0"}
pyreadline3 = "^3.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

#[tool.poetry.scripts]
#test = "python manage.py test"
