# Generated by Django 3.2.9 on 2021-11-14 19:41
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_auto_20211106_2121"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="day",
            name="text",
        ),
        migrations.AddField(
            model_name="day",
            name="meals",
            field=models.ManyToManyField(to="planner.Meal"),
        ),
    ]
