# Generated by Django 3.2.9 on 2021-11-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0006_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="meal",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="meal",
            name="categories",
            field=models.ManyToManyField(to="planner.Category"),
        ),
    ]
