# Generated by Django 3.2.9 on 2021-11-18 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0007_auto_20211118_2041"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="persons",
            field=models.PositiveSmallIntegerField(
                default=4, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="rating",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(5)]
            ),
        ),
    ]
