# Generated by Django 3.2.9 on 2022-09-14 18:48
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0008_auto_20211118_2220"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="categories",
            field=models.ManyToManyField(blank=True, to="planner.Category"),
        ),
    ]
