# Generated by Django 3.2.9 on 2022-09-20 18:23
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0009_alter_meal_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="is_recipe",
            field=models.BooleanField(default=False),
        ),
    ]
