name: Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: mysecretkey
      # Loaded in settings.py to set database configuration
      DATABASE_URL: postgres://postgres:postgres@127.0.0.1/github_actions
      # Disables SSL for the database in settings.py
      ENV: development
    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: psycopg2 prerequisites
      run: sudo apt-get install libpq-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
    - name: Install playwright
      run: playwright install
    - name: Run migrations
      run: poetry run python manage.py migrate
    - name: Collect static files
      run: poetry run python manage.py collectstatic
    - name: Run tests
      run: poetry run coverage run --source="." manage.py test
    - name: Produce coverage.xml
      run: poetry run coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
